// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Country is the predicate function for country builders.
type Country func(*sql.Selector)

// Language is the predicate function for language builders.
type Language func(*sql.Selector)

// Nationality is the predicate function for nationality builders.
type Nationality func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
