root = "."
testdata_dir = "testdata"
tmp_dir = "cmd/tmp"

[build]
cmd = "go build -o ./cmd/tmp/main cmd/main.go"
full_bin = "APP_ENV=dev APP_USER=air ./cmd/tmp/main"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = ["rest.http"]
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = false
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = "orange"
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
