name: Build and Publish Docker Image
on:
  push:
    # branches: [master, staging]

jobs:
  run-tests:
    uses: "./.github/workflows/tests.yml"
  build-and-publish-dev-image-to-dockerhub:
    needs: run-tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && ${{github.ref == 'refs/heads/staging'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - name: "Build docker image for dev server - Branch: Dev and Publish to Dockerhub registry"
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name:  <username>/<project-name>
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          platforms: linux/amd64,linux/arm64
          dockerfile: Dockerfile.prod
          default_branch: staging
          tags: "api.dev" 
  build-and-publish-production-image-to-dockerhub:
    needs: run-tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && ${{github.ref == 'refs/heads/master'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - name: "Build docker image for prod server - Branch: Master and Publish to Dockerhub registry"
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: <username>/<project-name>
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          platforms: linux/amd64,linux/arm64
          dockerfile: Dockerfile.prod
          default_branch: master
          tags: "api.prod"         
